if [ -d /etc/X11/xinit/xinitrc.d ]; then
for f in /etc/X11/xinit/xinitrc.d/*; do
[ -x "$f" ] && . "$f"
done
unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

xcape -e 'Caps_Lock=Escape;Control_L=Escape;Control_R=Escape'
setxkbmap -model pc105 -layout us,ru -variant ,,qwerty -option grp:toggle grp_led:caps setxkbmap -option 'caps:ctrl_modifier'
xmodmap ~/.Xmodmap
xbindkeys

exec i3
