HISTCONTROL=ignoreboth # ~ ignorespace:ignoredups
HISTFILE=~/.bash_histfile
HISTSIZE=100000
SAVEHIST=100000

# see https://github.com/wofr06/lesspipe
export LESSOPEN="|/usr/local/bin/lesspipe.sh %s" LESS_ADVANCED_PREPROCESSOR=1

[[ -f ~/.dotsecrets/secret_tokens ]] && . ~/.dotsecrets/secret_tokens

. '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc'
. '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc'

# haskell stack completions
eval "$(stack --bash-completion-script stack)"

# haskell summoner completions
source <(summon --bash-completion-script `which summon`)

[[ -f ~/.travis/travis.sh ]] && . ~/.travis/travis.sh
